apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: faction
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: elNDGLavd37Jp01jdv0WaRdaE0HvjXdcJJBsUVAVp2ICu9lpdbHfV9Zuc_uMbpd1LCbDhJmXzloNqkcqQ2oxmw
