
version: "3"
services:
  db:
    build: ./factiondb
    ports:
      - "5432:5432"
    volumes:
      - /opt/faction/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=3ZRa5iuwC9dQZPAoYC_myJSKmaHeJa4TkEQz5Vm5tVz-n32g5dlnPLZjs3iJzGhmAd2qMUwsRWpDcmMt5qkc4A
  mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8080:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=hyDgyQ-KerSBwgM_WPwgC7XAmluHYx4S-fDVJ3F1IQl1d1lDhSQvbBzzBbwdTeYwaC_HPwkpSjzSptv4ITIZxg
  console:
    build: ../services/console
    ports:
      - "443:443"
    depends_on:
      - api
  api:
    build: ../services/api
    depends_on:
      - mq
      - db
    ports:
      - "5000:5000"
    volumes:
      - /opt/faction/uploads:/opt/faction/uploads
    environment:
      - API_UPLOAD_DIR=/opt/faction/uploads
      - FLASK_SECRET=tOzRdln4nIQ5HKoneQbbzIW6NAWYIH819ZJ2mJ9kS8ZRYIlHjokxz2AdphkUBuSokGG7IhWBu2PDBNW4xnz3uQ
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=faction
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=3ZRa5iuwC9dQZPAoYC_myJSKmaHeJa4TkEQz5Vm5tVz-n32g5dlnPLZjs3iJzGhmAd2qMUwsRWpDcmMt5qkc4A
      - RABBIT_HOST=mq
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=hyDgyQ-KerSBwgM_WPwgC7XAmluHYx4S-fDVJ3F1IQl1d1lDhSQvbBzzBbwdTeYwaC_HPwkpSjzSptv4ITIZxg
  core:
    build: ../services/core
    depends_on:
      - mq
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=faction
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=3ZRa5iuwC9dQZPAoYC_myJSKmaHeJa4TkEQz5Vm5tVz-n32g5dlnPLZjs3iJzGhmAd2qMUwsRWpDcmMt5qkc4A
      - RABBIT_HOST=mq
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=hyDgyQ-KerSBwgM_WPwgC7XAmluHYx4S-fDVJ3F1IQl1d1lDhSQvbBzzBbwdTeYwaC_HPwkpSjzSptv4ITIZxg
      - SYSTEM_USERNAME=system
      - SYSTEM_PASSWORD=Ki0LXn8dWjdfUDTC5fEgOvz4AvhxTV87HaY2PuagC4tzErF9vcQ-Rcy8oSKmABt6YCNTw_cYlL586-FosVsacg
  dotnet-build:
    build: ../services/dotnet-build
    depends_on:
      - core
      - api
    volumes:
      - /opt/faction:/opt/faction
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=faction
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=3ZRa5iuwC9dQZPAoYC_myJSKmaHeJa4TkEQz5Vm5tVz-n32g5dlnPLZjs3iJzGhmAd2qMUwsRWpDcmMt5qkc4A
      - RABBIT_HOST=mq
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=hyDgyQ-KerSBwgM_WPwgC7XAmluHYx4S-fDVJ3F1IQl1d1lDhSQvbBzzBbwdTeYwaC_HPwkpSjzSptv4ITIZxg
