
version: "3"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /opt/faction/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=faction
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=aWkW_NYTkT09cQ1xkeMYRbwPRArQkrf8mhq0VzeRf7_321Fzwn8Ma9whMXkYTRYoBCHx7EZyMCwTsjuiQzbLIw
  mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8080:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=tYIaj9zMfBNSsgQ3Sh_3jpQ8h9bCX8OeTY00t36ZhjDlLdHGracN_Zv0wMuSICSXTIaV42freDgnWAkTgkyoWA
  console:
    image: faction/console:latest
    ports:
      - "443:443"
    depends_on:
      - api
    volumes:
      - /opt/faction/certs:/opt/faction/certs
  api:
    image: faction/api:latest
    depends_on:
      - mq
      - db
    ports:
      - "5000:5000"
    volumes:
      - /opt/faction/uploads:/opt/faction/uploads
    environment:
      - API_UPLOAD_DIR=/opt/faction/uploads
      - FLASK_SECRET=zf5qZeKElpG8hnfwBhqILIKc9qVHBQR6FW61e3--oesczxe3h3WETkvMdyRwyf7HZR0NoEs3n5HJIs54t7fbzQ
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=faction
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=aWkW_NYTkT09cQ1xkeMYRbwPRArQkrf8mhq0VzeRf7_321Fzwn8Ma9whMXkYTRYoBCHx7EZyMCwTsjuiQzbLIw
      - RABBIT_HOST=mq
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=tYIaj9zMfBNSsgQ3Sh_3jpQ8h9bCX8OeTY00t36ZhjDlLdHGracN_Zv0wMuSICSXTIaV42freDgnWAkTgkyoWA
  core:
    image: faction/core:latest
    depends_on:
      - mq
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=faction
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=aWkW_NYTkT09cQ1xkeMYRbwPRArQkrf8mhq0VzeRf7_321Fzwn8Ma9whMXkYTRYoBCHx7EZyMCwTsjuiQzbLIw
      - RABBIT_HOST=mq
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=tYIaj9zMfBNSsgQ3Sh_3jpQ8h9bCX8OeTY00t36ZhjDlLdHGracN_Zv0wMuSICSXTIaV42freDgnWAkTgkyoWA
      - SYSTEM_USERNAME=system
      - SYSTEM_PASSWORD=X5p5-4ht2ZYvTefS7sXwEDXkKEp4Rd7juz4V3ZinorSapxKTgY1ts3m-WzBKDPXZBOqNzZf-27MdmekAIZ9LlA
  build-dotnet:
    image: faction/build-dotnet:latest
    depends_on:
      - core
      - api
    volumes:
      - /opt/faction:/opt/faction
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=faction
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=aWkW_NYTkT09cQ1xkeMYRbwPRArQkrf8mhq0VzeRf7_321Fzwn8Ma9whMXkYTRYoBCHx7EZyMCwTsjuiQzbLIw
      - RABBIT_HOST=mq
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=tYIaj9zMfBNSsgQ3Sh_3jpQ8h9bCX8OeTY00t36ZhjDlLdHGracN_Zv0wMuSICSXTIaV42freDgnWAkTgkyoWA
