apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/send-timeout: "3600"
    nginx.org/websocket-services: "faction-hasura"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: faction-ingress
spec:
  rules:
    - host: www.faction
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: faction-console
                port:
                  number: 80
          - path: /api/v1/auth/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: faction-auth
                port:
                  number: 5000
          - path: /api/(v1/graphql.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: faction-hasura
                port:
                  number: 8080
          - path: /api/v1/files/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: faction-files
                port:
                  number: 5000
